Update ITI-55.html
IHE/publications pull request #495
Opened 2024-12-03 14:54 UTC by Ben-Levy-62

## 📑 CP Integration CP-ITI-1304

2024-12-03 16:03 UTC, JohnMoehrke commented
partial address #491

2024-12-06 10:45 UTC, dbabato requested changes
see comments

2024-12-06 12:15 UTC, JohnMoehrke commented on ITI/TF/Volume2/ITI-55.html
> +      <p>If the Responding Gateway serves results from multiple communities, and the Initiating Gateway specified a target community in which to search results as described in section 3.55.4.1.2.5, t
yes. I fixed

2024-12-06 12:16 UTC, JohnMoehrke commented on ITI/TF/Volume2/ITI-55.html
> +      <p>If the Initiating Gateway specified a target community as specified in section 3.55.4.1.2.5, then the Responding Gateway SHOULD include only RegistrationEvents with homeCommunityIds that mat
yes, I fixed

2024-12-06 15:20 UTC, dbabato approved these changes

2024-12-06 15:20 UTC, dbabato commented
Reviewed and found as Okay

2024-12-06 15:20 UTC, merged