Vol1 vol2 iti xds cp iti 1301
IHE/publications pull request #496
Opened 2024-12-03 15:11 UTC by Ben-Levy-62

## 📑 CP Integration CP-ITI-1301

2024-12-03 21:32 UTC, Ben-Levy-62 commented
In ITI-18, the li at 2454 does not have a /li to terminate it.  When I add one at 2468, all the surrounding list stuff breaks.  I also changed "XDS Registrys" to "XDS Registries".

2024-12-03 22:17 UTC, JohnMoehrke commented
> In ITI-18, the li at 2454 does not have a /li to terminate it. When I add one at 2468, all the surrounding list stuff breaks. I also changed "XDS Registrys" to "XDS Registries".

I think I fixed this.

2024-12-03 23:45 UTC, JohnMoehrke commented
@Ben-Levy-62 I further refined the bullets in that section. The encoding was really difficult to follow, it is now simple nesting. I started at 1 because number at zero is roman numerals.

2024-12-06 08:56 UTC, gregoriocanal commented on ITI/TF/Volume1/ch-10.html
> +	 <li class="bullet-list0">In queries in which the “$targetCommunityIdList” is specified, the Document Consumer shall not use the “$home” parameter.</li>
in the CP this bullet says:
In queries in which the “$targetCommunityIdList” is specified, the Document Consumer shall not populate the “home” attribute on the AdhocQuery element.

2024-12-06 08:59 UTC, gregoriocanal commented on ITI/TF/Volume1/ch-10.html
> +      <p>Note that when addressing the query to the Initiating Gateway, the Document Consumer that specifies the “$targetCommunityIdList” parameter must be aware that the Initiating Gateway may not s
i suggest to put a reference on see section 3.18.4.1.2.5

e.g. See Section <a href="../Volume2/ITI-18.html#3.18.4.1.2.5">ITI TF-2:3.18.4.1.2.5</a> Compatibility of Options.

2024-12-06 09:39 UTC, gregoriocanal requested changes
see comments

2024-12-06 09:39 UTC, gregoriocanal commented on ITI/TF/Volume1/ch-10.html
> +	 <li class="bullet-list0">In queries in which the “$targetCommunityIdList” is specified, the Document Consumer shall not use the “$home” parameter.</li>
in the CP the bullet says:
In queries in which the “$targetCommunityIdList” is specified, the Document Consumer shall not populate the “home” attribute on the AdhocQuery element.

2024-12-06 09:39 UTC, gregoriocanal commented on ITI/TF/Volume1/ch-10.html
> +      <p>Note that when addressing the query to the Initiating Gateway, the Document Consumer that specifies the “$targetCommunityIdList” parameter must be aware that the Initiating Gateway may not s
i suggest to put a reference on see section 3.18.4.1.2.5

e.g. See Section [ITI TF-2:3.18.4.1.2.5](https://github.com/IHE/publications/pull/Volume2/ITI-18.html#3.18.4.1.2.5) Compatibility of Options.

2024-12-06 09:39 UTC, gregoriocanal commented on ITI/TF/Volume2/ITI-18.html
>                  <p class="heading8" id="3.18.4.1.2.3.7.3">3.18.4.1.2.3.7.3 FindFolders</p>
FindFolders adHocQuery is missing the $targetCommunityIdList parameter in the table. line 948

2024-12-06 09:39 UTC, gregoriocanal commented on ITI/TF/Volume2/ITI-18.html
> +                            <li class="bullet-list1">If the Document Consume does support the On-Demand Documents Option<, then
as written in the cp change this line in:
If the Document Consumer does support the On-Demand Documents Option,

2024-12-06 09:39 UTC, gregoriocanal commented on ITI/TF/Volume2/ITI-18.html
> +                                        will get more results than is expected (See Section 3.38.4.1.3.1).
suggest to put an html reference on Section 3.38.4.1.3.1

2024-12-06 12:20 UTC, JohnMoehrke commented
@gregoriocanal your recommendations seem reasonable. Can you make the updates to this PR?

2024-12-06 14:45 UTC, gregoriocanal approved these changes
updated as requested

2024-12-06 15:08 UTC, merged