Vol1 vol2 iti dsub cp iti 1315
IHE/publications pull request #502
Opened 2024-12-04 00:18 UTC by Ben-Levy-62

## 📑 CP Integration of CP-ITI-1315 on DSUB.

2024-12-04 00:20 UTC, Ben-Levy-62 commented
Please check Table 26.5-1 carefully.  Row heights are specified in there because of copy/paste.  Not sure they should be there.  Please also make sure I did the rowspans correctly.  Thanks!!

2024-12-04 00:32 UTC, JohnMoehrke commented
supports #491

2024-12-06 10:00 UTC, gregoriocanal requested changes
see comments

2024-12-06 10:00 UTC, gregoriocanal commented on ITI/TF/Volume1/ch-26.html
>        <p>
this paragraph 333-338 should be below the table.

2024-12-06 10:00 UTC, gregoriocanal commented on ITI/TF/Volume1/ch-26.html
> +          <tr>
tabel heading shouldn't be bold?

2024-12-06 10:00 UTC, gregoriocanal commented on ITI/TF/Volume2/ITI-52.html
> +		(see Section 1:26.5 DSUB Security Considerations). The derived mitigations are as follows:</span>
i suggest to adda an html reference to 1.26.5 section

2024-12-06 10:00 UTC, gregoriocanal commented on ITI/TF/Volume2/ITI-53.html
> +        <span>The risk assessment for the Document Metadata Notify transaction is described in Table 1:26.5-1: DSUB risk assessment (see Section 1:26.5 DSUB Security Considerations). </span>
i suggest to add an html reference to 1.26.5 section

2024-12-06 10:00 UTC, gregoriocanal commented on ITI/TF/Volume2/ITI-54.html
> +        <span>The risk assessment for the Document Metadata Publish transaction is described in Table 1:26.5-1: DSUB risk assessment (see Section 1:26.5 DSUB Security Considerations). </span>
i suggest to adda an html reference to 1.26.5 section

2024-12-06 15:10 UTC, gregoriocanal approved these changes
updated as suggested

2024-12-06 15:12 UTC, merged

2024-12-06 15:17 UTC, gregoriocanal commented
Reviewed and updated as needed